import type { TaskGraphInput } from './types';

export const SIMPLE_CHAIN_INPUT: TaskGraphInput = {
  pools: [],
  tasks: [
    { id: 't1', name: 'Design schema', poolId: null, status: 'success' },
    { id: 't2', name: 'Run migration', poolId: null, status: 'working' },
    { id: 't3', name: 'Backfill data', poolId: null, status: 'open' },
    { id: 't4', name: 'Verify counts', poolId: null, status: 'blocked' },
  ],
  dependencies: [
    { fromId: 't2', toId: 't1' },
    { fromId: 't3', toId: 't2' },
    { fromId: 't4', toId: 't3' },
  ],
};

export const PARALLEL_DEPS_INPUT: TaskGraphInput = {
  pools: [],
  tasks: [
    { id: 'root', name: 'Decompose work', poolId: null, status: 'success' },
    { id: 'a1', name: 'Frontend slice', poolId: null, status: 'working' },
    { id: 'a2', name: 'Backend slice', poolId: null, status: 'open' },
    { id: 'a3', name: 'Infra slice', poolId: null, status: 'waiting' },
    { id: 'merge', name: 'Integrate', poolId: null, status: 'blocked' },
  ],
  dependencies: [
    { fromId: 'a1', toId: 'root' },
    { fromId: 'a2', toId: 'root' },
    { fromId: 'a3', toId: 'root' },
    { fromId: 'merge', toId: 'a1' },
    { fromId: 'merge', toId: 'a2' },
    { fromId: 'merge', toId: 'a3' },
  ],
};

export const ALL_STATUSES_INPUT: TaskGraphInput = {
  pools: [],
  tasks: [
    { id: 'blocked', name: 'Blocked task', poolId: null, status: 'blocked' },
    { id: 'open', name: 'Open task', poolId: null, status: 'open' },
    { id: 'working', name: 'Working task', poolId: null, status: 'working' },
    { id: 'waiting', name: 'Waiting task', poolId: null, status: 'waiting' },
    { id: 'success', name: 'Done task', poolId: null, status: 'success' },
    { id: 'failure', name: 'Failed task', poolId: null, status: 'failure' },
  ],
  dependencies: [],
};

export const SINGLE_POOL_INPUT: TaskGraphInput = {
  pools: [{ id: 'pool-a', name: 'Backend bootstrapping', parentPoolId: null }],
  tasks: [
    { id: 'pre', name: 'Approve plan', poolId: null, status: 'success' },
    { id: 'p1', name: 'Define types', poolId: 'pool-a', status: 'success' },
    { id: 'p2', name: 'Wire datastore', poolId: 'pool-a', status: 'working' },
    { id: 'p3', name: 'Add handlers', poolId: 'pool-a', status: 'blocked' },
    { id: 'post', name: 'Smoke test', poolId: null, status: 'blocked' },
  ],
  dependencies: [
    { fromId: 'pool-a', toId: 'pre' },
    { fromId: 'p2', toId: 'p1' },
    { fromId: 'p3', toId: 'p2' },
    { fromId: 'post', toId: 'pool-a' },
  ],
};

export const DEEPLY_NESTED_INPUT: TaskGraphInput = {
  pools: [
    { id: 'outer', name: 'Migration epic', parentPoolId: null },
    { id: 'inner-a', name: 'Schema', parentPoolId: 'outer' },
    { id: 'inner-b', name: 'Backfill', parentPoolId: 'outer' },
  ],
  tasks: [
    { id: 'root1', name: 'Discovery', poolId: null, status: 'success' },
    { id: 'inner-a-1', name: 'Add table', poolId: 'inner-a', status: 'success' },
    { id: 'inner-a-2', name: 'Add columns', poolId: 'inner-a', status: 'working' },
    { id: 'inner-b-1', name: 'Backfill batch 1', poolId: 'inner-b', status: 'open' },
    { id: 'inner-b-2', name: 'Backfill batch 2', poolId: 'inner-b', status: 'blocked' },
    { id: 'root2', name: 'Cutover', poolId: null, status: 'blocked' },
  ],
  dependencies: [
    { fromId: 'outer', toId: 'root1' },
    { fromId: 'root2', toId: 'outer' },
    { fromId: 'inner-a-2', toId: 'inner-a-1' },
    { fromId: 'inner-b', toId: 'inner-a' },
    { fromId: 'inner-b-2', toId: 'inner-b-1' },
  ],
};

export const COMPLEX_INPUT: TaskGraphInput = {
  pools: [
    { id: 'discovery', name: 'Discovery', parentPoolId: null },
    { id: 'build', name: 'Build', parentPoolId: null },
    { id: 'qa', name: 'QA', parentPoolId: null },
    { id: 'backend', name: 'Backend', parentPoolId: 'build' },
    { id: 'frontend', name: 'Frontend', parentPoolId: 'build' },
    { id: 'schema', name: 'Schema', parentPoolId: 'backend' },
    { id: 'api', name: 'API', parentPoolId: 'backend' },
    { id: 'components', name: 'Components', parentPoolId: 'frontend' },
    { id: 'pages', name: 'Pages', parentPoolId: 'frontend' },
    { id: 'smoke', name: 'Smoke', parentPoolId: 'qa' },
  ],
  tasks: [
    { id: 'kickoff', name: 'Kickoff', poolId: null, status: 'success' },
    { id: 'launch', name: 'Launch', poolId: null, status: 'blocked' },
    { id: 'research', name: 'User research', poolId: 'discovery', status: 'success' },
    { id: 'spike', name: 'Tech spike', poolId: 'discovery', status: 'success' },
    { id: 'spec', name: 'Spec', poolId: 'discovery', status: 'success' },
    { id: 'glue', name: 'Glue', poolId: 'build', status: 'waiting' },
    { id: 'migration', name: 'Migration script', poolId: 'backend', status: 'working' },
    { id: 'smoke-runner', name: 'Smoke runner', poolId: 'backend', status: 'blocked' },
    { id: 'add-tables', name: 'Add tables', poolId: 'schema', status: 'success' },
    { id: 'add-indexes', name: 'Add indexes', poolId: 'schema', status: 'working' },
    { id: 'endpoints', name: 'Endpoints', poolId: 'api', status: 'working' },
    { id: 'auth', name: 'Auth', poolId: 'api', status: 'open' },
    { id: 'rate-limit', name: 'Rate limiting', poolId: 'api', status: 'blocked' },
    { id: 'theme', name: 'Theme', poolId: 'frontend', status: 'waiting' },
    { id: 'buttons', name: 'Buttons', poolId: 'components', status: 'success' },
    { id: 'forms', name: 'Forms', poolId: 'components', status: 'success' },
    { id: 'modals', name: 'Modals', poolId: 'components', status: 'working' },
    { id: 'dashboard', name: 'Dashboard', poolId: 'pages', status: 'open' },
    { id: 'settings', name: 'Settings', poolId: 'pages', status: 'blocked' },
    { id: 'onboarding', name: 'Onboarding', poolId: 'pages', status: 'blocked' },
    { id: 'load-test', name: 'Load test', poolId: 'qa', status: 'blocked' },
    { id: 'security', name: 'Security audit', poolId: 'qa', status: 'failure' },
    { id: 'auth-tests', name: 'Auth tests', poolId: 'smoke', status: 'open' },
    { id: 'api-tests', name: 'API tests', poolId: 'smoke', status: 'open' },
    { id: 'ui-tests', name: 'UI tests', poolId: 'smoke', status: 'blocked' },
  ],
  dependencies: [
    { fromId: 'discovery', toId: 'kickoff' },
    { fromId: 'build', toId: 'discovery' },
    { fromId: 'qa', toId: 'build' },
    { fromId: 'launch', toId: 'qa' },
    { fromId: 'spike', toId: 'research' },
    { fromId: 'spec', toId: 'spike' },
    { fromId: 'frontend', toId: 'backend' },
    { fromId: 'glue', toId: 'frontend' },
    { fromId: 'glue', toId: 'backend' },
    { fromId: 'api', toId: 'schema' },
    { fromId: 'migration', toId: 'schema' },
    { fromId: 'smoke-runner', toId: 'migration' },
    { fromId: 'smoke-runner', toId: 'api' },
    { fromId: 'add-indexes', toId: 'add-tables' },
    { fromId: 'auth', toId: 'endpoints' },
    { fromId: 'rate-limit', toId: 'endpoints' },
    { fromId: 'pages', toId: 'components' },
    { fromId: 'theme', toId: 'components' },
    { fromId: 'forms', toId: 'buttons' },
    { fromId: 'modals', toId: 'forms' },
    { fromId: 'settings', toId: 'dashboard' },
    { fromId: 'onboarding', toId: 'dashboard' },
    { fromId: 'load-test', toId: 'smoke' },
    { fromId: 'security', toId: 'smoke' },
    { fromId: 'api-tests', toId: 'auth-tests' },
    { fromId: 'ui-tests', toId: 'api-tests' },
  ],
};

export const HUGE_INPUT: TaskGraphInput = {
  pools: [
    { id: 'backend', name: 'Backend', parentPoolId: null },
    { id: 'frontend', name: 'Frontend', parentPoolId: null },
    { id: 'mobile', name: 'Mobile', parentPoolId: null },
    { id: 'design', name: 'Design', parentPoolId: null },
    { id: 'qa', name: 'QA', parentPoolId: null },
    { id: 'devops', name: 'DevOps', parentPoolId: null },
    { id: 'docs', name: 'Docs', parentPoolId: null },
    { id: 'marketing', name: 'Marketing', parentPoolId: null },
    { id: 'api', name: 'API', parentPoolId: 'backend' },
    { id: 'database', name: 'Database', parentPoolId: 'backend' },
    { id: 'workers', name: 'Workers', parentPoolId: 'backend' },
    { id: 'components', name: 'Components', parentPoolId: 'frontend' },
    { id: 'pages', name: 'Pages', parentPoolId: 'frontend' },
    { id: 'state', name: 'State', parentPoolId: 'frontend' },
    { id: 'ios', name: 'iOS', parentPoolId: 'mobile' },
    { id: 'android', name: 'Android', parentPoolId: 'mobile' },
    { id: 'unit', name: 'Unit', parentPoolId: 'qa' },
    { id: 'integration', name: 'Integration', parentPoolId: 'qa' },
    { id: 'e2e', name: 'E2E', parentPoolId: 'qa' },
  ],
  tasks: [
    { id: 'roadmap', name: 'Roadmap signed off', poolId: null, status: 'success' },
    { id: 'budget', name: 'Finalize budget', poolId: null, status: 'success' },
    { id: 'kickoff', name: 'Engineering kickoff', poolId: null, status: 'success' },
    { id: 'launch', name: 'Launch', poolId: null, status: 'blocked' },
    { id: 'monitoring', name: 'Monitoring', poolId: 'backend', status: 'working' },
    { id: 'alerting', name: 'Alerting', poolId: 'backend', status: 'open' },
    { id: 'api-auth', name: 'Auth', poolId: 'api', status: 'success' },
    { id: 'api-users', name: 'Users', poolId: 'api', status: 'working' },
    { id: 'api-orgs', name: 'Orgs', poolId: 'api', status: 'open' },
    { id: 'api-billing', name: 'Billing', poolId: 'api', status: 'blocked' },
    { id: 'api-search', name: 'Search', poolId: 'api', status: 'open' },
    { id: 'api-webhooks', name: 'Webhooks', poolId: 'api', status: 'waiting' },
    { id: 'db-schema', name: 'Schema', poolId: 'database', status: 'success' },
    { id: 'db-migrations', name: 'Migrations', poolId: 'database', status: 'working' },
    { id: 'db-indexes', name: 'Indexes', poolId: 'database', status: 'open' },
    { id: 'db-replicas', name: 'Replicas', poolId: 'database', status: 'blocked' },
    { id: 'db-backups', name: 'Backups', poolId: 'database', status: 'open' },
    { id: 'wk-queue', name: 'Queue', poolId: 'workers', status: 'success' },
    { id: 'wk-scheduler', name: 'Scheduler', poolId: 'workers', status: 'working' },
    { id: 'wk-processors', name: 'Processors', poolId: 'workers', status: 'blocked' },
    { id: 'wk-retries', name: 'Retries', poolId: 'workers', status: 'blocked' },
    { id: 'fe-theme', name: 'Theme', poolId: 'frontend', status: 'success' },
    { id: 'cmp-button', name: 'Button', poolId: 'components', status: 'success' },
    { id: 'cmp-input', name: 'Input', poolId: 'components', status: 'success' },
    { id: 'cmp-modal', name: 'Modal', poolId: 'components', status: 'success' },
    { id: 'cmp-table', name: 'Table', poolId: 'components', status: 'working' },
    { id: 'cmp-form', name: 'Form', poolId: 'components', status: 'working' },
    { id: 'cmp-toast', name: 'Toast', poolId: 'components', status: 'open' },
    { id: 'cmp-menu', name: 'Menu', poolId: 'components', status: 'open' },
    { id: 'cmp-tabs', name: 'Tabs', poolId: 'components', status: 'waiting' },
    { id: 'pg-dashboard', name: 'Dashboard', poolId: 'pages', status: 'working' },
    { id: 'pg-settings', name: 'Settings', poolId: 'pages', status: 'open' },
    { id: 'pg-profile', name: 'Profile', poolId: 'pages', status: 'open' },
    { id: 'pg-billing', name: 'Billing', poolId: 'pages', status: 'blocked' },
    { id: 'pg-org', name: 'Org', poolId: 'pages', status: 'blocked' },
    { id: 'pg-admin', name: 'Admin', poolId: 'pages', status: 'blocked' },
    { id: 'st-store', name: 'Store', poolId: 'state', status: 'success' },
    { id: 'st-sync', name: 'Sync', poolId: 'state', status: 'working' },
    { id: 'st-cache', name: 'Cache', poolId: 'state', status: 'open' },
    { id: 'mb-push', name: 'Push notifications', poolId: 'mobile', status: 'open' },
    { id: 'mb-deeplinks', name: 'Deep links', poolId: 'mobile', status: 'blocked' },
    { id: 'ios-shell', name: 'Shell', poolId: 'ios', status: 'working' },
    { id: 'ios-auth', name: 'Auth', poolId: 'ios', status: 'open' },
    { id: 'ios-home', name: 'Home', poolId: 'ios', status: 'blocked' },
    { id: 'ios-payments', name: 'Payments', poolId: 'ios', status: 'blocked' },
    { id: 'ios-tests', name: 'Tests', poolId: 'ios', status: 'blocked' },
    { id: 'and-shell', name: 'Shell', poolId: 'android', status: 'working' },
    { id: 'and-auth', name: 'Auth', poolId: 'android', status: 'open' },
    { id: 'and-home', name: 'Home', poolId: 'android', status: 'blocked' },
    { id: 'and-payments', name: 'Payments', poolId: 'android', status: 'blocked' },
    { id: 'and-tests', name: 'Tests', poolId: 'android', status: 'blocked' },
    { id: 'd-research', name: 'Research', poolId: 'design', status: 'success' },
    { id: 'd-wires', name: 'Wireframes', poolId: 'design', status: 'success' },
    { id: 'd-mockups', name: 'Mockups', poolId: 'design', status: 'working' },
    { id: 'd-proto', name: 'Prototype', poolId: 'design', status: 'open' },
    { id: 'd-system', name: 'Design system', poolId: 'design', status: 'working' },
    { id: 'ut-auth', name: 'Auth tests', poolId: 'unit', status: 'open' },
    { id: 'ut-api', name: 'API tests', poolId: 'unit', status: 'blocked' },
    { id: 'ut-state', name: 'State tests', poolId: 'unit', status: 'blocked' },
    { id: 'ut-db', name: 'DB tests', poolId: 'unit', status: 'blocked' },
    { id: 'it-auth', name: 'Auth flow', poolId: 'integration', status: 'blocked' },
    { id: 'it-billing', name: 'Billing flow', poolId: 'integration', status: 'blocked' },
    { id: 'it-search', name: 'Search flow', poolId: 'integration', status: 'blocked' },
    { id: 'it-webhooks', name: 'Webhook flow', poolId: 'integration', status: 'failure' },
    { id: 'e2e-login', name: 'Login', poolId: 'e2e', status: 'blocked' },
    { id: 'e2e-signup', name: 'Signup', poolId: 'e2e', status: 'blocked' },
    { id: 'e2e-dash', name: 'Dashboard', poolId: 'e2e', status: 'blocked' },
    { id: 'e2e-settings', name: 'Settings', poolId: 'e2e', status: 'blocked' },
    { id: 'e2e-billing', name: 'Billing', poolId: 'e2e', status: 'blocked' },
    { id: 'do-ci', name: 'CI pipeline', poolId: 'devops', status: 'success' },
    { id: 'do-cd', name: 'CD pipeline', poolId: 'devops', status: 'working' },
    { id: 'do-monitoring', name: 'Monitoring', poolId: 'devops', status: 'open' },
    { id: 'do-alerts', name: 'Alerts', poolId: 'devops', status: 'blocked' },
    { id: 'do-scaling', name: 'Scaling', poolId: 'devops', status: 'blocked' },
    { id: 'doc-api', name: 'API docs', poolId: 'docs', status: 'open' },
    { id: 'doc-user', name: 'User guide', poolId: 'docs', status: 'blocked' },
    { id: 'doc-onboarding', name: 'Onboarding', poolId: 'docs', status: 'blocked' },
    { id: 'doc-release', name: 'Release notes', poolId: 'docs', status: 'blocked' },
    { id: 'doc-faq', name: 'FAQ', poolId: 'docs', status: 'blocked' },
    { id: 'mk-landing', name: 'Landing page', poolId: 'marketing', status: 'working' },
    { id: 'mk-blog', name: 'Blog post', poolId: 'marketing', status: 'open' },
    { id: 'mk-email', name: 'Email blast', poolId: 'marketing', status: 'blocked' },
    { id: 'mk-social', name: 'Social posts', poolId: 'marketing', status: 'blocked' },
    { id: 'mk-video', name: 'Demo video', poolId: 'marketing', status: 'blocked' },
  ],
  dependencies: [
    { fromId: 'budget', toId: 'roadmap' },
    { fromId: 'kickoff', toId: 'budget' },
    { fromId: 'backend', toId: 'kickoff' },
    { fromId: 'frontend', toId: 'kickoff' },
    { fromId: 'mobile', toId: 'kickoff' },
    { fromId: 'design', toId: 'kickoff' },
    { fromId: 'devops', toId: 'kickoff' },
    { fromId: 'qa', toId: 'backend' },
    { fromId: 'qa', toId: 'frontend' },
    { fromId: 'docs', toId: 'backend' },
    { fromId: 'marketing', toId: 'design' },
    { fromId: 'launch', toId: 'qa' },
    { fromId: 'launch', toId: 'mobile' },
    { fromId: 'launch', toId: 'marketing' },
    { fromId: 'launch', toId: 'docs' },
    { fromId: 'api', toId: 'database' },
    { fromId: 'workers', toId: 'database' },
    { fromId: 'monitoring', toId: 'api' },
    { fromId: 'alerting', toId: 'monitoring' },
    { fromId: 'api-users', toId: 'api-auth' },
    { fromId: 'api-orgs', toId: 'api-users' },
    { fromId: 'api-billing', toId: 'api-orgs' },
    { fromId: 'api-search', toId: 'api-users' },
    { fromId: 'api-webhooks', toId: 'api-orgs' },
    { fromId: 'db-migrations', toId: 'db-schema' },
    { fromId: 'db-indexes', toId: 'db-migrations' },
    { fromId: 'db-replicas', toId: 'db-indexes' },
    { fromId: 'db-backups', toId: 'db-migrations' },
    { fromId: 'wk-scheduler', toId: 'wk-queue' },
    { fromId: 'wk-processors', toId: 'wk-scheduler' },
    { fromId: 'wk-retries', toId: 'wk-processors' },
    { fromId: 'pages', toId: 'components' },
    { fromId: 'pages', toId: 'state' },
    { fromId: 'fe-theme', toId: 'components' },
    { fromId: 'cmp-form', toId: 'cmp-input' },
    { fromId: 'cmp-modal', toId: 'cmp-button' },
    { fromId: 'cmp-table', toId: 'cmp-button' },
    { fromId: 'cmp-toast', toId: 'cmp-button' },
    { fromId: 'cmp-menu', toId: 'cmp-button' },
    { fromId: 'cmp-tabs', toId: 'cmp-button' },
    { fromId: 'pg-settings', toId: 'pg-dashboard' },
    { fromId: 'pg-profile', toId: 'pg-dashboard' },
    { fromId: 'pg-billing', toId: 'pg-dashboard' },
    { fromId: 'pg-org', toId: 'pg-dashboard' },
    { fromId: 'pg-admin', toId: 'pg-dashboard' },
    { fromId: 'st-sync', toId: 'st-store' },
    { fromId: 'st-cache', toId: 'st-store' },
    { fromId: 'android', toId: 'ios' },
    { fromId: 'mb-push', toId: 'ios' },
    { fromId: 'mb-deeplinks', toId: 'mb-push' },
    { fromId: 'ios-auth', toId: 'ios-shell' },
    { fromId: 'ios-home', toId: 'ios-auth' },
    { fromId: 'ios-payments', toId: 'ios-auth' },
    { fromId: 'ios-tests', toId: 'ios-home' },
    { fromId: 'and-auth', toId: 'and-shell' },
    { fromId: 'and-home', toId: 'and-auth' },
    { fromId: 'and-payments', toId: 'and-auth' },
    { fromId: 'and-tests', toId: 'and-home' },
    { fromId: 'd-wires', toId: 'd-research' },
    { fromId: 'd-mockups', toId: 'd-wires' },
    { fromId: 'd-proto', toId: 'd-mockups' },
    { fromId: 'd-system', toId: 'd-mockups' },
    { fromId: 'integration', toId: 'unit' },
    { fromId: 'e2e', toId: 'integration' },
    { fromId: 'ut-api', toId: 'ut-auth' },
    { fromId: 'ut-state', toId: 'ut-auth' },
    { fromId: 'ut-db', toId: 'ut-auth' },
    { fromId: 'it-billing', toId: 'it-auth' },
    { fromId: 'it-search', toId: 'it-auth' },
    { fromId: 'it-webhooks', toId: 'it-auth' },
    { fromId: 'e2e-signup', toId: 'e2e-login' },
    { fromId: 'e2e-dash', toId: 'e2e-login' },
    { fromId: 'e2e-settings', toId: 'e2e-dash' },
    { fromId: 'e2e-billing', toId: 'e2e-dash' },
    { fromId: 'do-cd', toId: 'do-ci' },
    { fromId: 'do-monitoring', toId: 'do-cd' },
    { fromId: 'do-alerts', toId: 'do-monitoring' },
    { fromId: 'do-scaling', toId: 'do-cd' },
    { fromId: 'doc-user', toId: 'doc-api' },
    { fromId: 'doc-onboarding', toId: 'doc-user' },
    { fromId: 'doc-release', toId: 'doc-api' },
    { fromId: 'doc-faq', toId: 'doc-user' },
    { fromId: 'mk-blog', toId: 'mk-landing' },
    { fromId: 'mk-email', toId: 'mk-landing' },
    { fromId: 'mk-social', toId: 'mk-landing' },
    { fromId: 'mk-video', toId: 'mk-landing' },
  ],
};

export const CROSS_POOL_INPUT: TaskGraphInput = {
  pools: [
    { id: 'plan', name: 'Plan', parentPoolId: null },
    { id: 'build', name: 'Build', parentPoolId: null },
    { id: 'qa', name: 'QA', parentPoolId: null },
  ],
  tasks: [
    { id: 'plan-1', name: 'RFC draft', poolId: 'plan', status: 'success' },
    { id: 'plan-2', name: 'Review', poolId: 'plan', status: 'success' },
    { id: 'build-1', name: 'Backend', poolId: 'build', status: 'working' },
    { id: 'build-2', name: 'Frontend', poolId: 'build', status: 'open' },
    { id: 'qa-1', name: 'Smoke tests', poolId: 'qa', status: 'blocked' },
    { id: 'qa-2', name: 'Sign-off', poolId: 'qa', status: 'blocked' },
  ],
  dependencies: [
    { fromId: 'plan-2', toId: 'plan-1' },
    { fromId: 'build', toId: 'plan' },
    { fromId: 'qa', toId: 'build' },
    { fromId: 'build-2', toId: 'build-1' },
    { fromId: 'qa-2', toId: 'qa-1' },
  ],
};
