import { handler as listAgentCallsHandler } from './handlers/agent.calls.list.handler';
import { handler as readAgentCallHandler } from './handlers/agent.calls.read.handler';
import { handler as recordAgentCallHandler } from './handlers/agent.calls.record.handler';
import { handler as completeAgentHandler } from './handlers/agent.complete.handler';
import { handler as createAgentHandler } from './handlers/agent.create.handler';
import { handler as failAgentHandler } from './handlers/agent.fail.handler';
import { handler as freshStartAgentHandler } from './handlers/agent.fresh-start.handler';
import { handler as launchAgentHandler } from './handlers/agent.launch.handler';
import { handler as listAgentsHandler } from './handlers/agent.list.handler';
import { handler as sendAgentMessageHandler } from './handlers/agent.message.handler';
import { handler as listAgentPriceLineItemsHandler } from './handlers/agent.price-line-items.list.handler';
import { handler as recordAgentPriceLineItemHandler } from './handlers/agent.price-line-items.record.handler';
import { handler as readAgentHandler } from './handlers/agent.read.handler';
import { handler as renameAgentHandler } from './handlers/agent.rename.handler';
import { handler as resumeAgentHandler } from './handlers/agent.resume.handler';
import { handler as listAgentSignalsHandler } from './handlers/agent.signals.list.handler';
import { handler as resolveAgentSignalHandler } from './handlers/agent.signals.resolve.handler';
import { handler as sendAgentSignalHandler } from './handlers/agent.signals.send.handler';
import { handler as stopAgentHandler } from './handlers/agent.stop.handler';
import { handler as callAgentToolHandler } from './handlers/agent.tool.call.handler';
import { handler as listAgentTracesHandler } from './handlers/agent.traces.list.handler';
import { handler as recordAgentTraceHandler } from './handlers/agent.traces.record.handler';
import { handler as createAgentRegistryHandler } from './handlers/agent-registries.create.handler';
import { handler as deleteAgentRegistryHandler } from './handlers/agent-registries.delete.handler';
import { handler as listAgentRegistriesHandler } from './handlers/agent-registries.list.handler';
import { handler as updateAgentRegistryHandler } from './handlers/agent-registries.update.handler';
import { handler as readAppSettingsHandler } from './handlers/app-settings.read.handler';
import { handler as updateAppSettingsHandler } from './handlers/app-settings.update.handler';
import { handler as getDaemonStatusHandler } from './handlers/daemon.status.handler';
import { handler as describeDatabaseHandler } from './handlers/database.describe.handler';
import { handler as migrateDatabaseHandler } from './handlers/database.migrate.handler';
import { handler as openDatabaseHandler } from './handlers/database.open.handler';
import { handler as runDatabaseQueryHandler } from './handlers/database.query.handler';
import { handler as listDebugLogsHandler } from './handlers/debug.logs.list.handler';
import { handler as openDebugLogHandler } from './handlers/debug.logs.open.handler';
import { handler as openDebugLogsDirectoryHandler } from './handlers/debug.logs.open-directory.handler';
import { handler as readDebugLogHandler } from './handlers/debug.logs.read.handler';
import { handler as createDocumentHandler } from './handlers/documents.create.handler';
import { handler as deleteDocumentHandler } from './handlers/documents.delete.handler';
import { handler as listDocumentsHandler } from './handlers/documents.list.handler';
import { handler as readDocumentHandler } from './handlers/documents.read.handler';
import { handler as updateDocumentHandler } from './handlers/documents.update.handler';
import { handler as generateSpeechHandler } from './handlers/generate-speech.handler';
import { handler as createInferenceProfileHandler } from './handlers/inference-profiles.create.handler';
import { handler as deleteInferenceProfileHandler } from './handlers/inference-profiles.delete.handler';
import { handler as listInferenceProfilesHandler } from './handlers/inference-profiles.list.handler';
import { handler as updateInferenceProfileHandler } from './handlers/inference-profiles.update.handler';
import { handler as createIntegrationHandler } from './handlers/integrations.create.handler';
import { handler as deleteIntegrationHandler } from './handlers/integrations.delete.handler';
import { handler as listIntegrationsHandler } from './handlers/integrations.list.handler';
import { handler as updateIntegrationHandler } from './handlers/integrations.update.handler';
import { handler as listMetricNamesHandler } from './handlers/metrics.list-names.handler';
import { handler as listMetricVariantsHandler } from './handlers/metrics.list-variants.handler';
import { handler as queryMetricsAggregatedHandler } from './handlers/metrics.query-aggregated.handler';
import { handler as createRepositoryHandler } from './handlers/repositories.create.handler';
import { handler as deleteRepositoryHandler } from './handlers/repositories.delete.handler';
import { handler as listRepositoriesHandler } from './handlers/repositories.list.handler';
import { handler as updateRepositoryHandler } from './handlers/repositories.update.handler';
import { handler as createTaskBoardHandler } from './handlers/task-boards.create.handler';
import { handler as deleteTaskBoardHandler } from './handlers/task-boards.delete.handler';
import { handler as listTaskBoardsHandler } from './handlers/task-boards.list.handler';
import { handler as updateTaskBoardHandler } from './handlers/task-boards.update.handler';
import { handler as listTaskDeliverableSubmissionsHandler } from './handlers/task-deliverable-submissions.list.handler';
import { handler as submitTaskDeliverableHandler } from './handlers/task-deliverable-submissions.submit.handler';
import { handler as listTaskDeliverablesHandler } from './handlers/task-deliverables.list.handler';
import { handler as createTaskDependencyHandler } from './handlers/task-dependencies.create.handler';
import { handler as deleteTaskDependencyHandler } from './handlers/task-dependencies.delete.handler';
import { handler as listTaskDependenciesHandler } from './handlers/task-dependencies.list.handler';
import { handler as listTaskDispatchSettingsHandler } from './handlers/task-dispatch-settings.list.handler';
import { handler as readTaskDispatchSettingsHandler } from './handlers/task-dispatch-settings.read.handler';
import { handler as updateTaskDispatchSettingsHandler } from './handlers/task-dispatch-settings.update.handler';
import { handler as listTaskEventsHandler } from './handlers/task-events.list.handler';
import { handler as createTaskPoolHandler } from './handlers/task-pools.create.handler';
import { handler as deleteTaskPoolHandler } from './handlers/task-pools.delete.handler';
import { handler as listTaskPoolsHandler } from './handlers/task-pools.list.handler';
import { handler as createTaskTemplateDeliverableHandler } from './handlers/task-template-deliverables.create.handler';
import { handler as deleteTaskTemplateDeliverableHandler } from './handlers/task-template-deliverables.delete.handler';
import { handler as listTaskTemplateDeliverablesHandler } from './handlers/task-template-deliverables.list.handler';
import { handler as updateTaskTemplateDeliverableHandler } from './handlers/task-template-deliverables.update.handler';
import { handler as createTaskTemplateHandler } from './handlers/task-templates.create.handler';
import { handler as deleteTaskTemplateHandler } from './handlers/task-templates.delete.handler';
import { handler as listTaskTemplatesHandler } from './handlers/task-templates.list.handler';
import { handler as readTaskTemplateHandler } from './handlers/task-templates.read.handler';
import { handler as updateTaskTemplateHandler } from './handlers/task-templates.update.handler';
import { handler as createTaskHandler } from './handlers/tasks.create.handler';
import { handler as delegateTaskHandler } from './handlers/tasks.delegate.handler';
import { handler as deleteTaskHandler } from './handlers/tasks.delete.handler';
import { handler as listTasksHandler } from './handlers/tasks.list.handler';
import { handler as renameTaskHandler } from './handlers/tasks.rename.handler';
import { handler as undelegateTaskHandler } from './handlers/tasks.undelegate.handler';
import { handler as setTaskStatusHandler } from './handlers/tasks.update.handler';
import { handler as updateTaskDescriptionHandler } from './handlers/tasks.update-description.handler';
import { handler as createThirdPartyAgentInstallHandler } from './handlers/third-party-agent-installs.create.handler';
import { handler as deleteThirdPartyAgentInstallHandler } from './handlers/third-party-agent-installs.delete.handler';
import { handler as detectClaudeCodeInstallHandler } from './handlers/third-party-agent-installs.detect-claude-code.handler';
import { handler as listThirdPartyAgentInstallsHandler } from './handlers/third-party-agent-installs.list.handler';
import { handler as updateThirdPartyAgentInstallHandler } from './handlers/third-party-agent-installs.update.handler';
import { handler as readThreadSnapshotHandler } from './handlers/thread.snapshot.read.handler';
import { handler as listThreadsHandler } from './handlers/threads.list.handler';
import { handler as transcribeAudioHandler } from './handlers/transcribe-audio.handler';
import { handler as listWorkspacesHandler } from './handlers/workspaces.list.handler';
import { handler as createWorktreeHandler } from './handlers/worktrees.create.handler';
import { handler as deleteWorktreeHandler } from './handlers/worktrees.delete.handler';
import { handler as listWorktreesHandler } from './handlers/worktrees.list.handler';
import { handler as openWorktreeHandler } from './handlers/worktrees.open.handler';
import type { DaemonHandlerContext, DaemonOperationHandler, DaemonOperationName } from './types';

export type RegisterDaemonOperation = <TName extends DaemonOperationName>(
  operation: TName,
  handler: DaemonOperationHandler<TName>,
) => void;

/**
 * Wires every daemon handler into the bridge for one connected client.
 * Owning this list in a single file keeps `two-pebble-daemon.ts` short
 * and makes adding new operations a one-line append next to the matching
 * handler import.
 */
export function registerDaemonHandlers(context: DaemonHandlerContext, register: RegisterDaemonOperation): void {
  register('completeAgent', completeAgentHandler(context));
  register('createAgent', createAgentHandler(context));
  register('failAgent', failAgentHandler(context));
  register('launchAgent', launchAgentHandler(context));
  register('sendAgentMessage', sendAgentMessageHandler(context));
  register('sendAgentSignal', sendAgentSignalHandler(context));
  register('resolveAgentSignal', resolveAgentSignalHandler(context));
  register('listAgentSignals', listAgentSignalsHandler(context));
  register('listAgentCalls', listAgentCallsHandler(context));
  register('listAgentPriceLineItems', listAgentPriceLineItemsHandler(context));
  register('listAgentTraces', listAgentTracesHandler(context));
  register('listAgents', listAgentsHandler(context));
  register('readAgent', readAgentHandler(context));
  register('renameAgent', renameAgentHandler(context));
  register('stopAgent', stopAgentHandler(context));
  register('resumeAgent', resumeAgentHandler(context));
  register('freshStartAgent', freshStartAgentHandler(context));
  register('readAgentCall', readAgentCallHandler(context));
  register('recordAgentCall', recordAgentCallHandler(context));
  register('recordAgentPriceLineItem', recordAgentPriceLineItemHandler(context));
  register('recordAgentTrace', recordAgentTraceHandler(context));
  register('callAgentTool', callAgentToolHandler(context));
  register('describeDatabase', describeDatabaseHandler(context));
  register('migrateDatabase', migrateDatabaseHandler(context));
  register('openDatabase', openDatabaseHandler(context));
  register('runDatabaseQuery', runDatabaseQueryHandler(context));
  register('createInferenceProfile', createInferenceProfileHandler(context));
  register('deleteInferenceProfile', deleteInferenceProfileHandler(context));
  register('listInferenceProfiles', listInferenceProfilesHandler(context));
  register('updateInferenceProfile', updateInferenceProfileHandler(context));
  register('createIntegration', createIntegrationHandler(context));
  register('deleteIntegration', deleteIntegrationHandler(context));
  register('listDebugLogs', listDebugLogsHandler(context));
  register('listIntegrations', listIntegrationsHandler(context));
  register('openDebugLog', openDebugLogHandler(context));
  register('openDebugLogsDirectory', openDebugLogsDirectoryHandler(context));
  register('readDebugLog', readDebugLogHandler(context));
  register('readThreadSnapshot', readThreadSnapshotHandler(context));
  register('listThreads', listThreadsHandler(context));
  register('updateIntegration', updateIntegrationHandler(context));
  register('listRepositories', listRepositoriesHandler(context));
  register('createRepository', createRepositoryHandler(context));
  register('updateRepository', updateRepositoryHandler(context));
  register('deleteRepository', deleteRepositoryHandler(context));
  register('listDocuments', listDocumentsHandler(context));
  register('createDocument', createDocumentHandler(context));
  register('readDocument', readDocumentHandler(context));
  register('updateDocument', updateDocumentHandler(context));
  register('deleteDocument', deleteDocumentHandler(context));
  register('listWorktrees', listWorktreesHandler(context));
  register('createWorktree', createWorktreeHandler(context));
  register('deleteWorktree', deleteWorktreeHandler(context));
  register('openWorktree', openWorktreeHandler(context));
  register('listWorkspaces', listWorkspacesHandler(context));
  register('listAgentRegistries', listAgentRegistriesHandler(context));
  register('createAgentRegistry', createAgentRegistryHandler(context));
  register('updateAgentRegistry', updateAgentRegistryHandler(context));
  register('deleteAgentRegistry', deleteAgentRegistryHandler(context));
  register('readAppSettings', readAppSettingsHandler(context));
  register('updateAppSettings', updateAppSettingsHandler(context));
  register('transcribeAudio', transcribeAudioHandler(context));
  register('generateSpeech', generateSpeechHandler(context));
  register('listThirdPartyAgentInstalls', listThirdPartyAgentInstallsHandler(context));
  register('createThirdPartyAgentInstall', createThirdPartyAgentInstallHandler(context));
  register('updateThirdPartyAgentInstall', updateThirdPartyAgentInstallHandler(context));
  register('deleteThirdPartyAgentInstall', deleteThirdPartyAgentInstallHandler(context));
  register('detectClaudeCodeInstall', detectClaudeCodeInstallHandler(context));
  register('getDaemonStatus', getDaemonStatusHandler(context));
  register('listTaskBoards', listTaskBoardsHandler(context));
  register('createTaskBoard', createTaskBoardHandler(context));
  register('updateTaskBoard', updateTaskBoardHandler(context));
  register('deleteTaskBoard', deleteTaskBoardHandler(context));
  register('listTaskPools', listTaskPoolsHandler(context));
  register('createTaskPool', createTaskPoolHandler(context));
  register('deleteTaskPool', deleteTaskPoolHandler(context));
  register('listTasks', listTasksHandler(context));
  register('createTask', createTaskHandler(context));
  register('delegateTask', delegateTaskHandler(context));
  register('undelegateTask', undelegateTaskHandler(context));
  register('renameTask', renameTaskHandler(context));
  register('setTaskStatus', setTaskStatusHandler(context));
  register('updateTaskDescription', updateTaskDescriptionHandler(context));
  register('deleteTask', deleteTaskHandler(context));
  register('listTaskDependencies', listTaskDependenciesHandler(context));
  register('createTaskDependency', createTaskDependencyHandler(context));
  register('deleteTaskDependency', deleteTaskDependencyHandler(context));
  register('listTaskEvents', listTaskEventsHandler(context));
  register('readTaskDispatchSettings', readTaskDispatchSettingsHandler(context));
  register('listTaskDispatchSettings', listTaskDispatchSettingsHandler(context));
  register('updateTaskDispatchSettings', updateTaskDispatchSettingsHandler(context));
  register('listTaskTemplates', listTaskTemplatesHandler(context));
  register('createTaskTemplate', createTaskTemplateHandler(context));
  register('readTaskTemplate', readTaskTemplateHandler(context));
  register('updateTaskTemplate', updateTaskTemplateHandler(context));
  register('deleteTaskTemplate', deleteTaskTemplateHandler(context));
  register('listTaskTemplateDeliverables', listTaskTemplateDeliverablesHandler(context));
  register('createTaskTemplateDeliverable', createTaskTemplateDeliverableHandler(context));
  register('updateTaskTemplateDeliverable', updateTaskTemplateDeliverableHandler(context));
  register('deleteTaskTemplateDeliverable', deleteTaskTemplateDeliverableHandler(context));
  register('listTaskDeliverables', listTaskDeliverablesHandler(context));
  register('listTaskDeliverableSubmissions', listTaskDeliverableSubmissionsHandler(context));
  register('submitTaskDeliverable', submitTaskDeliverableHandler(context));
  register('listMetricNames', listMetricNamesHandler(context));
  register('listMetricVariants', listMetricVariantsHandler(context));
  register('queryMetricsAggregated', queryMetricsAggregatedHandler(context));
}
