export const WORKFLOW_LAYOUT = {
  NODE_WIDTH: 200,
  NODE_HEIGHT: 40,
  COL_GAP: 40,
  ROW_GAP: 16,
  CHILD_ITEM_HEIGHT: 28,
  CHILD_GAP_FROM_PARENT: 12,
  CHILD_ARROW_GAP: 8,
  GROUP_ITEM_HEIGHT: 32,
} as const;
