// This file is generated. Edit scripts/generate-openrouter-pricing.ts and rerun:
//   bun scripts/generate-openrouter-pricing.ts
//
// Source: https://openrouter.ai/api/v1/models
// Pricing is converted from per-token USD into per-million-token (PPM) USD.

import type { PriceCalculator } from '../price-calculator';
import { registerOpenRouterPricingPart1 } from './openrouter-1';
import { registerOpenRouterPricingPart2 } from './openrouter-2';
import { registerOpenRouterPricingPart3 } from './openrouter-3';
import { registerOpenRouterPricingPart4 } from './openrouter-4';
import { registerOpenRouterPricingPart5 } from './openrouter-5';
import { registerOpenRouterPricingPart6 } from './openrouter-6';
import { registerOpenRouterPricingPart7 } from './openrouter-7';
import { registerOpenRouterPricingPart8 } from './openrouter-8';
import { registerOpenRouterPricingPart9 } from './openrouter-9';
import { registerOpenRouterPricingPart10 } from './openrouter-10';
import { registerOpenRouterPricingPart11 } from './openrouter-11';
import { registerOpenRouterPricingPart12 } from './openrouter-12';
import { registerOpenRouterPricingPart13 } from './openrouter-13';
import { registerOpenRouterPricingPart14 } from './openrouter-14';
import { registerOpenRouterPricingPart15 } from './openrouter-15';
import { registerOpenRouterPricingPart16 } from './openrouter-16';
import { registerOpenRouterPricingPart17 } from './openrouter-17';
import { registerOpenRouterPricingPart18 } from './openrouter-18';
import { registerOpenRouterPricingPart19 } from './openrouter-19';
import { registerOpenRouterPricingPart20 } from './openrouter-20';
import { registerOpenRouterPricingPart21 } from './openrouter-21';
import { registerOpenRouterPricingPart22 } from './openrouter-22';
import { registerOpenRouterPricingPart23 } from './openrouter-23';
import { registerOpenRouterPricingPart24 } from './openrouter-24';
import { registerOpenRouterPricingPart25 } from './openrouter-25';
import { registerOpenRouterPricingPart26 } from './openrouter-26';
import { registerOpenRouterPricingPart27 } from './openrouter-27';
import { registerOpenRouterPricingPart28 } from './openrouter-28';
import { registerOpenRouterPricingPart29 } from './openrouter-29';
import { registerOpenRouterPricingPart30 } from './openrouter-30';
import { registerOpenRouterPricingPart31 } from './openrouter-31';
import { registerOpenRouterPricingPart32 } from './openrouter-32';
import { registerOpenRouterPricingPart33 } from './openrouter-33';
import { registerOpenRouterPricingPart34 } from './openrouter-34';
import { registerOpenRouterPricingPart35 } from './openrouter-35';
import { registerOpenRouterPricingPart36 } from './openrouter-36';
import { registerOpenRouterPricingPart37 } from './openrouter-37';
import { registerOpenRouterPricingPart38 } from './openrouter-38';
import { registerOpenRouterPricingPart39 } from './openrouter-39';
import { registerOpenRouterPricingPart40 } from './openrouter-40';
import { registerOpenRouterPricingPart41 } from './openrouter-41';
import { registerOpenRouterPricingPart42 } from './openrouter-42';
import { registerOpenRouterPricingPart43 } from './openrouter-43';
import { registerOpenRouterPricingPart44 } from './openrouter-44';
import { registerOpenRouterPricingPart45 } from './openrouter-45';
import { registerOpenRouterPricingPart46 } from './openrouter-46';

export function registerOpenRouterPricing(calculator: PriceCalculator) {
  registerOpenRouterPricingPart1(calculator);
  registerOpenRouterPricingPart2(calculator);
  registerOpenRouterPricingPart3(calculator);
  registerOpenRouterPricingPart4(calculator);
  registerOpenRouterPricingPart5(calculator);
  registerOpenRouterPricingPart6(calculator);
  registerOpenRouterPricingPart7(calculator);
  registerOpenRouterPricingPart8(calculator);
  registerOpenRouterPricingPart9(calculator);
  registerOpenRouterPricingPart10(calculator);
  registerOpenRouterPricingPart11(calculator);
  registerOpenRouterPricingPart12(calculator);
  registerOpenRouterPricingPart13(calculator);
  registerOpenRouterPricingPart14(calculator);
  registerOpenRouterPricingPart15(calculator);
  registerOpenRouterPricingPart16(calculator);
  registerOpenRouterPricingPart17(calculator);
  registerOpenRouterPricingPart18(calculator);
  registerOpenRouterPricingPart19(calculator);
  registerOpenRouterPricingPart20(calculator);
  registerOpenRouterPricingPart21(calculator);
  registerOpenRouterPricingPart22(calculator);
  registerOpenRouterPricingPart23(calculator);
  registerOpenRouterPricingPart24(calculator);
  registerOpenRouterPricingPart25(calculator);
  registerOpenRouterPricingPart26(calculator);
  registerOpenRouterPricingPart27(calculator);
  registerOpenRouterPricingPart28(calculator);
  registerOpenRouterPricingPart29(calculator);
  registerOpenRouterPricingPart30(calculator);
  registerOpenRouterPricingPart31(calculator);
  registerOpenRouterPricingPart32(calculator);
  registerOpenRouterPricingPart33(calculator);
  registerOpenRouterPricingPart34(calculator);
  registerOpenRouterPricingPart35(calculator);
  registerOpenRouterPricingPart36(calculator);
  registerOpenRouterPricingPart37(calculator);
  registerOpenRouterPricingPart38(calculator);
  registerOpenRouterPricingPart39(calculator);
  registerOpenRouterPricingPart40(calculator);
  registerOpenRouterPricingPart41(calculator);
  registerOpenRouterPricingPart42(calculator);
  registerOpenRouterPricingPart43(calculator);
  registerOpenRouterPricingPart44(calculator);
  registerOpenRouterPricingPart45(calculator);
  registerOpenRouterPricingPart46(calculator);
}
